### ISSUE TITLE
Multi Cooler Get Fan Level

### ISSUE THREAD

**Issue by adolfomantis** [falahati/NvAPIWrapper#16]
Hi. Im tring to get fan level (%) in multi cooler gpus (RTX2070 and RTX2060 in my case) using last driver (441). Before this, I was using NvAPI_GPU_GetCoolerSettings funtions with single cooler gpus succesfully, but now, with multi coolers gpus functions returns -104 error (NVAPI_NOT_SUPPORTED).  I am tring to use Client GPU functions, with NvAPI_GPU_ClientFanCoolersGetInfo and using your structs and it works fine (returns 0 and info is according to two coolers and returns correct values for maximum RPM for each), but when I use NvAPI_GPU_ClientFanCoolersGetStatus or NvAPI_GPU_ClientFanCoolersGetControl with your structs, both funtions returns -5 for each case (NVAPI_INVALID_ARGUMENT)(So, structures and Versions are OK), i double checked funtions but i can not make works properly. Any clue? Thanks in advanced. Great Job. (Sorry for my english).

**Comment by falahati** [comment]
Issue #10 might be interesting to you.

Update to the latest version of library and try the high-level API as follow:

        var GPUs = PhysicalGPU.GetPhysicalGPUs();
        var Cool = GPUs[Index].CoolerInformation.Coolers;
        for (int j = 0; j < Cool.Count(); j++)
        {
            var speed = Cool[j].CurrentLevel;
            Console.WriteLine(speed);
        }

If this failed to work for you please notify me.

**Comment by falahati** [comment]
If you insist on using the low-level API, following is the list of methods that can help you with RTX cards:

```C#
GPUApi.GetClientFanCoolersInfo();
GPUApi.GetClientFanCoolersStatus();
GPUApi.GetClientFanCoolersControl();
```

**Comment by adolfomantis** [comment]
Thanks for your soon response. Yes, problem occurs in low-level API call. In GPUApi.GetClientFanCoolersInfo() function works very fine, NvAPI_Status = 0 and returns correct data (2 Coolers for count and Max RPM for each cooler), but when i try to use GPUApi.GetClientFanCoolersStatus() or GPUApi.GetClientFanCoolersControl() both funtions return error (NvAPI_status = -5 (NVAPI_INVALID_ARGUMENT)). I suspect nvapi changed data structures (to a new version o V2) in last drivers. I will try to find Nvidia Driver 410, Release, install it and i will try again. I will keep inform you. Thanks

**Comment by adolfomantis** [comment]
Problem persist with 425.11 driver version....

**Comment by MaynardMiner** [comment]
@adolfomantis 

https://github.com/MaynardMiner/SWARM/tree/master/build/apps/nvfans

try using this application, and let me know if it works. I have not had a user inform me that it is not working yet.

```
nvfans.exe -i [GPU_INDEX_NUMBER] -s [SPEED IN PERCENT]
```

code:

```
using System;
using System.Linq;
using ConsoleUtilities;
using NvAPIWrapper;
using NvAPIWrapper.GPU;
using CommandLine;

namespace nvfans
{
	class Program
	{
		public class Options
		{
			[Option('i', "index", Required = false, HelpText = "Target GPU.")]
			public int Index { get; set; }
			[Option('s', "speed", Required = false, HelpText = "Desired Command Speed.")]
			public int Speed { get; set; }
		}

		static void Main(string[] args)
		{
			int Index = -1;
			int Speed = -1;

			CommandLine.Parser.Default.ParseArguments<Options>(args)
			.WithParsed<Options>(o =>
			 {
				 if (o.Index > -1) { Index = o.Index; }
				 else {
					 Console.WriteLine("Argument Index invalid");
					 System.Environment.Exit(0);
				 }
				 if (o.Speed > -1 )
				 {
					 if(o.Speed < 101) { Speed = o.Speed; }
					 else
					 {
						 Console.WriteLine("Argument Speed invalid");
						 System.Environment.Exit(0);
					 }
				 }
			 });

			NVIDIA.Initialize();
			var GPUs = PhysicalGPU.GetPhysicalGPUs();
			var Cool = GPUs[Index].CoolerInformation.Coolers;
			var k = Cool.ToArray();
			for (int j = 0; j < k.Count(); j++)
			{
				GPUs[0].CoolerInformation.SetCoolerSettings(j, Speed);
				int test = GPUs[0].CoolerInformation.CurrentFanSpeedLevel;
				Console.WriteLine($"Current Fan speed: {test}");
				Console.WriteLine($"New Fan Speed: {Speed}");
			}
			Console.ReadKey();
		}

	}
}
```

**Comment by falahati** [comment]
> I suspect nvapi changed data structures (to a new version o V2) in last drivers.

If that's the case it means that old overclocking programs (like an older version of afterburner) would not work. If they decide to add new functionality they usually add a new structure with a new version which is then selected and acted upon when calling the API. Breaking all old programs is a bad move and I don't think they did that.

Invalid argument error is interesting. It might be that we missed something with the `PrivateFanCoolersStatusV1` and `PrivateFanCoolersControlV1` structures. And to be honest there is not much there to go wrong. Maybe one of the `_Reserved` fields or the `_UnknownUInt` field supposed to have some information we are missing. But the size of struct and the version should be correct as there is no STRUCT error. Please try changing the setting of the fans using a third-party application like the afterburner and see if in a specific configuration this app works. (locked mode; unlocked, etc)

Also, the MaynardMiner might be a good example of how you should get this information and change them. If it fails for you as well but every third party overclocking program works as expected, then there is something wrong with the implementation of the structures in the library and I can hopefully take a look at this with your held since I don't have access to any RTX card.

**Comment by falahati** [comment]
Closed due to inactivity
