### ISSUE TITLE
Data Structures and functions

### ISSUE THREAD

**Issue by adolfomantis** [falahati/NvAPIWrapper#17]
Sorry for delay in my response. @MaynardMiner, you lib and code works perfect, thanks. @falahati,  data structures are OK, problem is i was porting code and make a mistake porting your structures. About new version in structures, You are right, it is not a deal to break old programs with new structures, making old structures obsoletes. Problem is not with data structures but with functions. Navi arch does not support Fan Cooler Status Function (returns -104 Nvapi_not_supported), instead it is necessary to use Fan Client Functions (Status). I checked it using GTX1660, RTX2070 and RTX2060 GPUs with Fan Client Structures and ported code works very fine. It is possible Reserved or Unknown field are Flags for Data Supported (How knows? I do not have information about some Nvidia structures (Its a mistery for common people)). If you need to make some tests with Navi GPUs, let me know, will be my pleasure. Thanks.

**Comment by falahati** [comment]
NAVI arch is for AMD cards as far as I know. I think you mean the Turing Architecture.
I am happy to hear that you have solved the problem.
Yes, Turing devices seem to support three new methods instead of old methods used for reading the fan's status. That was why I suggested using the high-level API since it selects the right underlying method automatically. In any case, this project is fairly documented and I believe you should be able to port it to any language or framework with little effort.
