### ISSUE TITLE
Getting NVAPI_API_NOT_INITIALIZED

### ISSUE THREAD

**Issue by samjviana** [falahati/NvAPIWrapper#44]
Getting NVAPI_API_NOT_INITIALIZED.

The error only occurs on 1 of the computers that i've tested.
The computer has an GeForce 210 with 342.01 NVIDIA Driver.

Funny thing is that i have another computer with same GPU and driver version and it works fine.

**Comment by falahati** [comment]
The first thing you should do before using this library is to call `NVIDIA.Initialize()`. Are you doing this? If so please double-check the state of the program in regard to threads. Now I am not sure if NVAPI is sensitive to threads or not but it is a good idea to see if this is the problem.
Long time since I first wrote this library. :)

**Comment by samjviana** [comment]
It seems that the problema was the driver... I was calling `NVIDIA.Initialize()`, and looked if the problem was the threads.
Finally i decided to use DDU to completly remove current drivers and reinstall, and it worked.
Thanks !!
