### ISSUE TITLE
[Help wanted] Is there a way to CREATE/REMOVE a fake display using this wrapper?

### ISSUE THREAD

**Issue by guofengtd** [falahati/NvAPIWrapper#49]
It's so hard to get any useful information on this topic, days of time spent on google, and got nothing...

finally I got this wrapper, and could be a good choice :)

I'm very eager to know if you support this, thanks

**Comment by falahati** [comment]
what is a fake display? I don't think we have anything like that in NVidia APIs.
The only way you can make a fake display is to merge some other display devices into a virtual display device which is probably not what you are looking for.

otherwise you need one of these:
https://www.amazon.com/s?k=Display+Dummy+Plug+headless

**Comment by guofengtd** [comment]
thank you very much for your detailed reply

I think what I needed is EDID management

**Comment by falahati** [comment]
you can read and write EDID using `PhysicalGPU.ReadEDIDData()` and `PhysicalGPU.WriteEDIDData()`. But I don't believe this helps with creating a fake display. Reading or writing EDID needs to have an actual display or at least a dummy plug connected to that output.
