### ISSUE TITLE
Geforce MX150

### ISSUE THREAD

**Issue by yoyos** [falahati/NvAPIWrapper#60]
My laptop has two GPUs:

![image](https://user-images.githubusercontent.com/1993859/187940179-daed582f-9c8e-442c-9965-e29e50b915b2.png)

I'm trying to make my laptop screen and HDMI plugged screen recognized by NvAPIWrapper but it just sees nothing.

PhysicalGPU.GetPhysicalGPUs() seems to see my GPU
![image](https://user-images.githubusercontent.com/1993859/187942879-461648f4-79aa-43e5-9e99-97e797200a52.png)

Display.GetDisplays() sees nothing
![image](https://user-images.githubusercontent.com/1993859/187942384-adb9fb47-b021-4adc-b7b8-044be8a9814a.png)

PathInfo.GetDisplaysConfig()
`Nothing to show`

Is this normal ? I'm sure you already have an answer ;)

**Comment by falahati** [comment]
depends on the connection of devices. 
for a laptop using NVIDIA Optimus, the main display is usually drived by the iGPU rather than the dGPU. If your HDMI connection is also connected to the iGPU, it is expected to see no display device when using the NVIDIA API.

You can check this by opening the NVIDIA Control panel and checking the list of connected display devices.

For example, check out my setup, I have a laptop with an iGPU and an NVIDIA dGPU connected to two additional displays, one by the Thunderbolt port which is driven by the Intel Chipset and therefore the iGPU, and the other by the DisplayPort connected directly to the dGPU. The laptop's own display is connected to the iGPU and I can't change that. As you can see, NVIDIA Control Panel only sees the one display that is connected directly to it and none other:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/2479372/188152324-c8d7734e-f075-45f3-85e3-d376c22742a8.png">

**Comment by falahati** [comment]
closed due to inactivity

**Comment by yoyos** [comment]
Thanks @falahati 

I think I just have no port directly linked to dGPU like you say.

In Nvidia control pannel, there is no display menu like you:

![image](https://user-images.githubusercontent.com/1993859/188594466-bdb91afb-332f-453e-b007-e608fde7e5e8.png)

Have a nice day

**Comment by falahati** [comment]
thank you for confirming the source of the problem. nice day to you too
