### ISSUE TITLE
Compatibility with latest Nvidia drivers?  (re: age of project?)

### ISSUE THREAD

**Issue by sofakng** [falahati/NvAPIWrapper#68]
This looks to be a fantastic project!

However, it doesn't look like it's been updated in a few years.  This isn't necessarily a bad thing but I'm wondering if it's compatible with the latest Nvidia drivers and if anything new was added to NvAPI that isn't supported in this wrapper?

**Comment by falahati** [comment]
nvapi documentation is available here to compare:
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/index.html

apparently, there are some problems with game profiles due to an update to the nvapi sometimes encrypting the entries. other than that I don't remember any breaking change being introduced by them.
